import { Container, Text, Grid } from '@nextui-org/react'
import Head from 'next/head'
import Landing from '-/features/landing/landing'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sushiii </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
      </main>
    </>
  )
}
